# Generated by Django 3.1.2 on 2021-01-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicantname', models.CharField(max_length=100)),
                ('cnic', models.IntegerField(max_length=15)),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=30)),
                ('mstatus', models.CharField(max_length=30)),
                ('domicile', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=1000)),
                ('employment', models.CharField(default='', max_length=50)),
                ('nationality', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
