# Generated by Django 3.1.2 on 2021-01-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intro',
            old_name='applicantname',
            new_name='applicantsname',
        ),
    ]
