# Generated by Django 3.1.2 on 2021-01-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210118_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='cnic',
            field=models.IntegerField(),
        ),
    ]
