# Generated by Django 3.1.2 on 2021-01-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210118_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intro',
            old_name='adress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='applicantsname',
            new_name='Applicants_name',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='cnic',
            new_name='CNIC',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='domicile',
            new_name='Domicile',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='employment',
            new_name='Employment',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='fathername',
            new_name='Father_name',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='mstatus',
            new_name='Marital_status',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='mothername',
            new_name='Mother_name',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='nationality',
            new_name='Nationality',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='religion',
            new_name='Religion',
        ),
    ]
