# Generated by Django 3.1.2 on 2021-01-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210118_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='CNIC',
            field=models.CharField(max_length=15),
        ),
    ]
