# Generated by Django 3.1.2 on 2021-01-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210118_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='email',
            new_name='Email_address',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='phone_no',
            new_name='Phone_number',
        ),
        migrations.RemoveField(
            model_name='info',
            name='father',
        ),
        migrations.RemoveField(
            model_name='info',
            name='name',
        ),
    ]
