# Generated by Django 3.1.2 on 2021-01-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210118_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('cover1', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('cover2', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('pdf', models.FileField(upload_to='books/pdfs/')),
            ],
        ),
    ]
