# Generated by Django 3.1.2 on 2021-01-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='email',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='book',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='book',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='book',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='book',
            name='skill_4',
        ),
        migrations.RemoveField(
            model_name='book',
            name='skill_5',
        ),
        migrations.RemoveField(
            model_name='book',
            name='skillset',
        ),
        migrations.RemoveField(
            model_name='book',
            name='subject',
        ),
    ]
