# Generated by Django 3.1.2 on 2021-01-18 09:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210118_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pdf',
            new_name='certificate',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='degree',
        ),
        migrations.AddField(
            model_name='book',
            name='cv',
            field=models.FileField(default=datetime.datetime(2021, 1, 18, 9, 35, 14, 581085, tzinfo=utc), upload_to='books/pdfs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/'),
        ),
    ]
