# Generated by Django 3.1.2 on 2021-01-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210118_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='mydoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='books/pdfs/')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('certificate', models.FileField(upload_to='books/pdfs/')),
                ('degree', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
            ],
        ),
        migrations.DeleteModel(
            name='document',
        ),
    ]
