# Generated by Django 3.1.2 on 2021-01-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210118_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mydoc',
        ),
    ]
