# Generated by Django 3.1.2 on 2021-01-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mydoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='mydoc',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
