# Generated by Django 3.1.2 on 2021-02-28 18:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillset', multiselectfield.db.fields.MultiSelectField(choices=[('java', 'java'), ('c++', 'c++'), ('python', 'python'), ('c#', 'c#'), ('php', 'php')], default='', max_length=22)),
                ('skill_1', models.CharField(default='', max_length=50)),
                ('skill_2', models.CharField(default='', max_length=50)),
                ('skill_3', models.CharField(default='', max_length=50)),
                ('skill_4', models.CharField(default='', max_length=50)),
                ('skill_5', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
