# Generated by Django 3.1.2 on 2021-03-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='Gender',
            field=models.CharField(choices=[('0', 'Female'), ('1', 'male')], max_length=11),
        ),
    ]
