# Generated by Django 3.1.2 on 2021-03-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210301_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intro',
            name='Gender',
        ),
    ]
