# Generated by Django 3.1.2 on 2021-03-01 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_intro_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intro',
            name='Domicile',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='Marital_status',
        ),
    ]
