# Generated by Django 3.1.2 on 2021-03-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210301_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='rate',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=14),
        ),
    ]
