# Generated by Django 3.1.2 on 2021-03-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_skills_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='rate',
        ),
    ]
