# Generated by Django 3.1.2 on 2021-04-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydoc',
            name='facebook',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='mydoc',
            name='linkedin',
            field=models.URLField(default=''),
        ),
    ]
