# Generated by Django 3.1.2 on 2021-04-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210408_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydoc',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='mydoc',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='info',
            name='facebook',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='info',
            name='linkedin',
            field=models.URLField(default=''),
        ),
    ]
