# Generated by Django 3.1.2 on 2021-04-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210408_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Email_address',
            field=models.CharField(max_length=200),
        ),
    ]
