# Generated by Django 3.1.2 on 2021-04-08 06:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210408_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skill_1',
            new_name='Additional_skills',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skillset',
            new_name='Hands_on_programming_languages',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_4',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_5',
        ),
        migrations.AddField(
            model_name='skills',
            name='Interpersonal_skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('active listening', ''), ('teamwork', ''), ('Responsibility', 'Responsibility'), ('Dependability', 'Dependability'), ('Leadership', 'Leadership'), ('Motivation', 'Motivation'), ('Flexibility', 'Flexibility'), ('Patience', 'Patience'), ('Empathy', 'Empathy')], default='', max_length=105),
        ),
        migrations.AddField(
            model_name='skills',
            name='Intrapersonal_skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('self-esteem', 'self-esteem'), ('discipline', 'discipline'), ('brainstorming', 'brainstorming'), ('writing', 'writing'), ('communication', 'communication'), ('team building', 'team building')], default='', max_length=72),
        ),
    ]
