# Generated by Django 3.1.2 on 2021-04-08 06:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210408_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='Interpersonal_skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('active listening', 'active listening'), ('teamwork', 'teamwork'), ('Responsibility', 'Responsibility'), ('Dependability', 'Dependability'), ('Leadership', 'Leadership'), ('Motivation', 'Motivation'), ('Flexibility', 'Flexibility'), ('Patience', 'Patience'), ('Empathy', 'Empathy')], default='', max_length=105),
        ),
    ]
