# Generated by Django 3.1.2 on 2021-04-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210408_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutyou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
